name: toy_swapp
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Shared Packages
  shared_widgets: 
    git:
      url: https://github.com/SemihYlmzz/shared_widgets.git
      ref: main
  shared_constants: 
    git:
      url: https://github.com/SemihYlmzz/shared_constants.git
      ref: main
  

  # Current User Preferences Repository
  current_user_preferences_repository:
    path: packages/current_user_preferences_repository

  # Local Database API
  local_database_api:
    path: packages/local_database_api
    
  # Shared Preferences API
  shared_preferences_api:
    path: packages/shared_preferences_api

  # Animation
  flutter_animate: ^4.5.0

  # Annotations
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # Business Logic
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  
  # Dependency Injection
  provider: 6.1.2
  
  # Fonts
  google_fonts: ^6.2.1

  # Navigation
  go_router: ^13.2.2

  # Localization
  flutter_localizations:
    sdk: flutter
  
  # Loggers
  logging: ^1.2.0

  # Widgets
  styled_text: ^8.1.0

dev_dependencies:

  # Tests
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

  # Linting
  very_good_analysis: ^5.1.0

  # Code Generation
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
