name: toy_swapp
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Shared Packages
  shared_widgets: 
    git:
      url: https://github.com/SemihYlmzz/shared_widgets.git
      ref: main
  shared_constants: 
    git:
      url: https://github.com/SemihYlmzz/shared_constants.git
      ref: main
  

  # Repositories
  app_metadata_repository:
    path: packages/app_metadata_repository
  app_preferences_repository:
    path: packages/app_preferences_repository
  auth_repository:
    path: packages/auth_repository
  consumer_repository:
    path: packages/consumer_repository
  device_metadata_repository:
    path: packages/device_metadata_repository
  toy_repository:
    path: packages/toy_repository

  # Services
  permission_service:
    path: packages/permission_service
  image_service:
    path: packages/image_service
  location_service:
    path: packages/location_service

  # Apis
  remote_database:
    path: packages/remote_database
  remote_database_cloud_firestore:
    path: packages/remote_database_cloud_firestore
  cloud_storage:
    path: packages/cloud_storage
  cloud_storage_firebase_storage:
    path: packages/cloud_storage_firebase_storage

  
  # Animations
  flutter_animate: ^4.5.0
  animations: ^2.0.11
  
  # Annotations
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # Business Logic
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  bloc_concurrency: ^0.2.5
  # Core APIS
  firebase_core: ^2.28.0

  # Dart
  fpdart: ^1.1.0

  # Dependency Injection
  provider: ^6.1.2
  
  # Fonts
  google_fonts: ^6.2.1

  # # Localization
  # flutter_localizations:
  #   sdk: flutter

  # Loggers
  logging: ^1.2.0  

  # Navigation
  go_router: ^13.2.2

  # Splash Screen
  flutter_native_splash: ^2.4.0
  
  # Streams
  stream_transform: ^2.1.0

  # Widgets
  styled_text: ^8.1.0
  linkpeek: ^1.0.0
  flutter_touch_ripple: ^1.1.21
  smooth_page_indicator: ^1.1.0

dev_dependencies:

  # Tests
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

  # Linting
  very_good_analysis: ^5.1.0

  # Code Generation
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1

  # Splash Screen
flutter_native_splash:
  color: "#ffffff"
  image: assets/flame_logo.png
  color_dark: "#111111"
  image_dark: assets/flame_logo.png
  

flutter:
  uses-material-design: true
  # Generate for L10n File
  # generate: true

  assets:
    - assets/