name: current_user_preferences_repository
description: description
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # App For Failure
  toy_swapp:
    path: ../../

  # Local Database API
  local_database_api:
    path: ../local_database_api

  # Annotations
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # Dart Specific
  fpdart: ^1.1.0

dev_dependencies:
  very_good_analysis: ^5.1.0
  mocktail: ^1.0.0

  # Code Generation
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1